### ISSUE TITLE
Pin to git tag for phovea dependencies, or find a different approach

### ISSUE THREAD

**Issue by mccalluc** [phovea/phovea_vis#23]
We need to pin our phovea references, but it's not working right now: https://github.com/phovea/phovea_vis/pull/16#issuecomment-267175068. Why?

If we can't figure this out, maybe just use npm?

**Comment by sgratzl** [comment]
https://github.com/phovea/phovea_d3/blob/v0.0.1/package.json -> links to phovea_core master
phovea_d3 -> links to v0.0.1

since it is stated to match the exact version, npm correctly checkouts two different versions, master branch for phovea_d3 and v0.0.1 for phovea_d3. That results that the "same" core code but with different definitions should be compiled together. 

solution: phovea_d3 should also use the tagged version of the master

**Comment by mccalluc** [comment]
Fixed at 70478d55
